#!/usr/bin/env python3
"""Fetch broiler data for all 50 states from the NASS Census of Agriculture.

    export NASS_QUICKSTATS_KEY=...        # free key, quickstats.nass.usda.gov/api
    python tools/fetch_census_states.py > data/census_states.yaml

WHY THIS EXISTS
---------------
The NASS *survey* programme - both the Poultry Slaughter and the Production
and Value summaries - suppresses states where too few operations exist, to
avoid disclosing individual businesses. That caps state coverage at 22, and
it caps it in the API exactly as it does in the PDFs: querying the survey
series for 2025 returns the same 14 states plus a lumped "OTHER STATES".

The **Census of Agriculture** is a different programme with different
disclosure handling, and at state level for broilers it publishes **all 50
states with nothing withheld**. That is what takes this project from 22
states to 50, and it includes California - the 8th largest broiler state in
the country, which appears in no year of the survey data.

CAVEAT, and it matters
----------------------
Census is a five-yearly enumeration, not an annual survey, so these figures
are 2022 and will not move until the 2027 census. They are also SALES rather
than slaughter or production. Do not mix them into a time series with the
annual data - they answer "which states raise broilers, and roughly how
many" rather than "how many were slaughtered last year".

The key is read from the environment and never written to the output.
"""
from __future__ import annotations

import json
import os
import sys
import urllib.parse
import urllib.request

API = "https://quickstats.nass.usda.gov/api/api_GET/"

SERIES = {
    "sales_head": "CHICKENS, BROILERS - SALES, MEASURED IN HEAD",
    "operations": "CHICKENS, BROILERS - OPERATIONS WITH SALES",
    "inventory": "CHICKENS, BROILERS - INVENTORY",
}


def fetch(key: str, year: int) -> list[dict]:
    q = urllib.parse.urlencode({
        "key": key,
        "commodity_desc": "CHICKENS",
        "class_desc": "BROILERS",
        "source_desc": "CENSUS",
        "agg_level_desc": "STATE",
        "year": year,
        "format": "JSON",
    })
    with urllib.request.urlopen(f"{API}?{q}", timeout=120) as r:
        return json.load(r)["data"]


def main() -> int:
    key = os.environ.get("NASS_QUICKSTATS_KEY")
    if not key:
        print("set NASS_QUICKSTATS_KEY (free: quickstats.nass.usda.gov/api)",
              file=sys.stderr)
        return 1

    year = int(sys.argv[1]) if len(sys.argv) > 1 else 2022
    rows = fetch(key, year)

    # domain_desc TOTAL is the undifferentiated state figure; the other
    # domains break the same total down by operation size and would double
    # count if summed in.
    picked: dict[str, dict[str, str]] = {}
    for name, desc in SERIES.items():
        for r in rows:
            if r["short_desc"] == desc and r["domain_desc"] == "TOTAL":
                picked.setdefault(r["state_name"].title(), {})[name] = \
                    r["Value"].replace(",", "").strip()

    w = sys.stdout.write
    w("# Broiler presence and scale for ALL 50 STATES.\n"
      "#\n"
      "# GENERATED by tools/fetch_census_states.py - do not hand-edit.\n"
      "#\n"
      f"# Source: USDA NASS Census of Agriculture {year}, via the QuickStats\n"
      "# API. The census is a five-yearly enumeration rather than an annual\n"
      "# survey, and unlike the survey programme it publishes every state\n"
      "# with nothing suppressed.\n"
      "#\n"
      "# This is what lifts state coverage from 22 to 50. California is the\n"
      "# clearest example of what the survey hides: a top-ten broiler state\n"
      "# that appears in no year of the slaughter or production summaries.\n"
      "#\n"
      "# DO NOT mix these into a time series with the annual data. They are\n"
      "# SALES in a census year, not slaughter or production, and they will\n"
      f"# not change until the next census. Treat them as 'which states raise\n"
      "# broilers, and at what scale', which is precisely what the map needs.\n\n")
    w(f"source: nass-census-agriculture-{year}\nspecies: broiler\n"
      f"census_year: {year}\n\nregions:\n")

    def num(v: str | None) -> int | None:
        return int(v) if v and v.isdigit() else None

    for state in sorted(picked):
        d = picked[state]
        w(f"  - region: {state}\n")
        for field in ("sales_head", "operations", "inventory"):
            v = num(d.get(field))
            if v is not None:
                w(f"    {field}: {v}\n")

    withheld = sum(1 for d in picked.values()
                   if num(d.get("sales_head")) is None)
    print(f"{len(picked)} states, {withheld} with sales withheld",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
