#!/usr/bin/env python3
"""Parse the NASS "Poultry - Production and Value" summary into YAML.

    pdftotext -layout plva0426.pdf plva.txt
    python tools/parse_production_value.py plva.txt > data/production_value.yaml

This is a DIFFERENT publication from Poultry Slaughter. It measures broilers
PRODUCED (Dec 1 - Nov 30) rather than young chickens SLAUGHTERED (calendar
year), so the national totals legitimately differ and must never be summed.

Two reasons it is worth parsing:

  1. It independently confirms the state live weights we already hold.
     Production pounds divided by head reproduces the slaughter report's
     average live weight, from a separate survey with separate methodology.

  2. It recovers states. NASS suppresses different states in different years
     and different publications, so a union across both is larger than
     either alone.

Table bounds are located by their headings rather than hardcoded offsets,
because the row a table ends on moves between editions.
"""
from __future__ import annotations

import re
import sys

ROW = re.compile(r"^([A-Z][A-Za-z ,]+?)\s*\.{3,}\s*(.*)$")
NOT_A_STATE = {"United States", "Other States", "Other States 1"}


def find_tables(lines: list[str]) -> dict[int, tuple[int, int]]:
    """Locate each year's broiler table by its heading and its US total row."""
    starts = {}
    for i, ln in enumerate(lines):
        m = re.match(r"^Broiler Production and Value .*: (\d{4})\s*$", ln)
        if m:
            starts[int(m.group(1))] = i
    bounds = {}
    for year, start in starts.items():
        for j in range(start, len(lines)):
            s = lines[j].lstrip()
            if s.startswith("United States") and any(c.isdigit() for c in s):
                bounds[year] = (start, j + 1)
                break
    return bounds


def numbers(rest: str) -> list[float]:
    out = []
    for tok in re.split(r"\s{2,}", rest.strip()):
        t = tok.replace(",", "").strip()
        if re.fullmatch(r"\d+", t):
            out.append(float(t))
    return out


def parse(lines: list[str], a: int, b: int) -> dict[str, list[float]]:
    rows = {}
    for ln in lines[a:b]:
        m = ROW.match(ln)
        if not m:
            continue
        vals = numbers(m.group(2))
        if len(vals) == 3:
            rows[m.group(1).strip().rstrip(",")] = vals
    return rows


def main(path: str) -> int:
    lines = open(path, encoding="utf-8").read().splitlines()
    bounds = find_tables(lines)
    if not bounds:
        print("no broiler tables found", file=sys.stderr)
        return 1

    tables = {y: parse(lines, a, b) for y, (a, b) in bounds.items()}
    states = {y: {k: v for k, v in t.items() if k not in NOT_A_STATE}
              for y, t in tables.items()}
    national = {y: t.get("United States") for y, t in tables.items()}

    years = sorted(tables, reverse=True)
    union = sorted(set().union(*(states[y] for y in years)))

    w = sys.stdout.write
    w("# Broiler production, live weight, and value by state.\n"
      "#\n"
      "# GENERATED by tools/parse_production_value.py - do not hand-edit.\n"
      "#\n"
      "# Source: USDA NASS \"Poultry - Production and Value\" annual summary,\n"
      "# a different publication from Poultry Slaughter. It counts broilers\n"
      "# PRODUCED over Dec 1 - Nov 30; the slaughter report counts young\n"
      "# chickens SLAUGHTERED over the calendar year and also includes\n"
      "# roasters and capons. The national totals therefore differ - 9.40bn\n"
      "# produced against 9.58bn slaughtered in 2025 - and must not be summed\n"
      "# or treated as the same series.\n"
      "#\n"
      "# derived_live_weight_lb is production pounds divided by head. It\n"
      "# reproduces the slaughter report's state average live weight exactly,\n"
      "# which is the cross-check that makes this file worth carrying.\n"
      "#\n"
      "# The report excludes any state producing under 500,000 broilers, and\n"
      "# suppresses others to avoid disclosing individual operations. Which\n"
      "# states get suppressed CHANGES BY YEAR, so keeping every year widens\n"
      "# coverage.\n\n")
    w("source: nass-production-value-2025\nspecies: broiler\n\n")

    w("national:\n")
    for y in years:
        v = national.get(y)
        if not v:
            continue
        w(f"  - year: {y}\n"
          f"    head_thousands: {v[0]:.0f}\n"
          f"    live_weight_klb: {v[1]:.0f}\n"
          f"    value_kusd: {v[2]:.0f}\n")

    w("\nregions:\n")
    for y in years:
        for st in sorted(states[y]):
            h, lb, val = states[y][st]
            w(f"  - region: {st}\n"
              f"    year: {y}\n"
              f"    head_thousands: {h:.0f}\n"
              f"    live_weight_klb: {lb:.0f}\n"
              f"    value_kusd: {val:.0f}\n"
              f"    derived_live_weight_lb: {lb / h:.2f}\n")

    print(f"years {years}; states per year "
          f"{ {y: len(states[y]) for y in years} }; union {len(union)}",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1] if len(sys.argv) > 1 else "plva.txt"))
